FROM ubuntu:artful

ENV RUSTUP_HOME=/usr/local/rustup \
	CARGO_HOME=/usr/local/cargo \
	TOOLCHAIN_HOME=/usr/local/toolchain \
	PATH=/usr/local/cargo/bin:$PATH \
	TOOLCHAIN=wasm32-unknown-emscripten

RUN apt-get update && apt-get -y install curl gcc make xz-utils mtools gosu python git
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain none -y --no-modify-path
RUN rustup toolchain install stable
RUN rustup toolchain install nightly
RUN rustup default nightly
RUN rustup target add wasm32-unknown-unknown
RUN rustup component add rust-src
RUN cargo install wasm-bindgen-cli
RUN curl https://nodejs.org/dist/v9.7.1/node-v9.7.1-linux-x64.tar.xz | tar xfJ - -C /usr/local --strip-components=1
RUN mkdir -p $TOOLCHAIN_HOME

COPY entrypoint.sh /usr/local/bin/
ENTRYPOINT ["bash", "/usr/local/bin/entrypoint.sh"]
CMD ["/bin/bash"]
